### ISSUE TITLE
Add inSpan method for tracer

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-php#115]
Sometimes you need to instrument operations that are being performed by legacy code. E.g. http call to a service but instead of using a http standard library like guzzle, it is being done with raw curl. Those times, the effort to actually replace the curl call and use a new shiny and instrumented library like guzzle is already a big effort and it is very error prone.

In those cases, having a `Tracer::inSpan($options, $callable, $args)` method would be helpful as that method is going to do tracing around that legacy call without forcing you to touch the logic (more than passing the right variables into the callable). Does that sound a reasonable use case?

Initial feedback from @adriancole:

> I think there have been similar discussions around this.. sleuth has the ability to do this also py_zipkin. to a degree zipkin-js does (promise tracing)

Ping @adriancole @basvanbeek

**Comment by jcchavezs** [comment]
More info:

- `$options` will allow users to pass span name, tags and potentially a parent context (which might not be needed).
- Any expection being thrown inside the callable will be recorded as a tag error and will be pass up.
- The function will return whatever output comes from the callable.

**Comment by adriancole** [comment]
this type of utility has been discussed many times and has been around in various forms for at least 5 years. OpenCensus is probably not the one to cite for prior art in other words.

Most of the time, this is best to do in such a place that it can be an aspect. Because things like naming the span are not something you want in user code. If it has to be in user code, there's usually integrations for things like annotations:

ex 1: py_zipkin https://github.com/Yelp/py_zipkin#usage-3-log-a-span-inside-an-ongoing-trace
ex 2: sleuth https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_creating_new_spans

Some systems which have predefined lambda types also have helper utilities libraries.. of course there's still a problem with naming and tagging policy hence the above paragraph. Anyway zipkin-js has a utility for example, for promises

https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin#local-tracing

This feature is an alternative to just using normal apis, which force some of the questions to be answered, such as naming policy and exception handling. Ex the normal scoped span in brave:

https://github.com/openzipkin/brave/tree/master/brave#in-process-tracing

**Comment by adriancole** [comment]
one final note is that an http library is probably a bad example of something to do like this as most of the time local tracing utilities are for things like local commands. if you make an http call look like a local span then probably it will be confusing as it is lacking metadata like kind, remote service etc. So if a utility like this is made, highly recommend not putting in examples to do this for things like remote commands.

**Comment by jcchavezs** [comment]
Right. So this specific case is not probably the best example but is the
use case I found. It does not matter IMHO the kind here since this is more
of local tracing rather than actually http call because e.g. I am not even
thinking of propagating the context in http headers but agree this is a
confusing example because people might think that by doing so, http headers
are actually being propagated. Will refine the description of the issue and
potential use cases soon.

ons. 3. jul. 2019, 11:08 skrev Adrian Cole <notifications@github.com>:

**Comment by adriancole** [comment]
other interesting idea is here in aio where they setup the span and then close over a deferred result:  https://aiozipkin.readthedocs.io/en/latest/examples.html

Also, I don't know the facilities in php for meta programming or patching, but if there were any it would be a lot easier to intercept the calls you want and use a normal span. Ex in java there is aop and various bytecode approaches that allow folks to opt out of having to change the code.

Concretely, it looks something like this in java.. again no idea what'a available in php but probably the better first choice is to hide this from the end user code vs double-down on changing all of it with a slightly smaller api.

```java
    @Around("@annotation(traced)")
    public Object traceThing(ProceedingJoinPoint pjp, Traced traced) throws Throwable {
      // When there is no trace in progress, this overrides the decision based on the annotation
      Sampler decideUsingAnnotation = declarativeSampler.toSampler(traced);
      Tracer tracer = tracing.get().tracer().withSampler(decideUsingAnnotation);

      // This code looks the same as if there was no declarative override
      ScopedSpan span = tracer.startScopedSpan("");
      try {
        return pjp.proceed();
      } catch (RuntimeException | Error e) {
        span.error(e);
        throw e;
      } finally {
        span.finish();
      }
    }
```

hope this helps

**Comment by jcchavezs** [comment]
I have been thinking on this and I found it complicated enough to implement. My initial idea was that we could basically wrap a function call but there are many questions that can't be easily answered and more important, that can be answered in a way that covers all the cases. I like more the annotations idea but unforntunatelly PHP does not support annotations natively so it is usually related to frameworks that allow interceptors (like in https://github.com/jcchavezs/zipkin-instrumentation-symfony/issues/3).

Hence I am closing this issue for now until a strong use case pops in.
