### ISSUE TITLE
Adds support for multiple tags in one call

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-php#124]
Right now tagging a span requires one tag per call:

```
$span->tag('key1', 'value1');
$span->tag('key2', 'value2');
```

also in https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/Middleware.php#L83

IMHO we could reduce some boilerplate if we could pass a map of tags for tagging. Also bear in mind that creating maps in PHP is fairly easy. Hence an API like would does the trick:

```
$span->tag(['key1' => 'value1', 'key2' => 'value2']);
```

Ping @adriancole

**Comment by adriancole** [comment]
I need a standing comment to put somewhere about questions relating to making utility functions over top the api, who they are serving etc. The usual response would be the same. Is this purely idiomatic? Is this performant? folks using the tracing api for instrumentation should know the answers or consider them when deciding what to put on the core tracer, to avoid extra memory caused by things like wrapping in collections just to avoid a newline.

otoh a simpler user-based api not for routine instrumentation, but for user things could make sense, but then you'd ask why are they doing multiple tags at the same time, which tags etc? This can help identify if the concern is truly user-level (business context) or just random methods on tracer.

**Comment by adriancole** [comment]
ps my above soliloquy is the questions to ask yourself. you make the call!
